background_opacity: 0.75

colors:
  primary:
    background: '#000000'
  normal:
    black:   '#2e3436'
    red:     '#cc6666'
    green:   '#67dd34'
    yellow:  '#ffcc00'
    blue:    '#729fcf'
    magenta: '#b294bb'
    cyan:    '#8abeb7'
    white:   '#c5c8c6'
  bright:
    black:   '#555753'
    red:     '#d54e53'
    green:   '#b9ca4a'
    yellow:  '#e7c547'
    blue:    '#7aa6da'
    magenta: '#c397d8'
    cyan:    '#70c0b1'
    white:   '#eaeaea'
  cursor:
    text:   '#ffffff'
    cursor: '#ff8c00'

cursor:
  style:
    shape: Block
    blinking: On

draw_bold_text_with_bright_colors: false

font:
    normal:
      family: JuliaMono
      style: RegularLatin
    bold:
      family: JuliaMono
      style: BoldLatin
    size: 13.0
    offset:
      y: 4

key_bindings:
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
  - { key: W, mods: Control|Shift, action: Quit }

mouse:
  hide_when_typing: true

window:
  dynamic_title: true
